services:
  opilochka.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro